version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '3020:3000'
        volumes:
            - /app/node_modules
            - .:/app
        command: ['pnpm', 'dev']
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        command: ['pnpm', 'run', 'test']
